export_plots: true

module_order:
    - fastqc:
        name: 'FastQC (library; raw)'
        info: 'This section of the report shows FastQC results before adapter trimming.'
        path_filters:
            - '*_fastqc.zip'
        path_filters_exclude:
            - '*trimmed_fastqc.zip'
    - fastp:
        name: 'Fastp (library; trimmed)'
        info: 'This section of the report shows fastp results.'
        path_filters:
            - '*_fastp.json'
    - fastqc:
        name: 'FastQC (library; trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
            - '*_trimmed_fastqc.zip'